config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "posts#index"

  resources :posts do 
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create, :edit, :update]

  get '/users/:id', :to => 'users#change_password'
  post '/users/:id', :to => 'users#update_password'

  resource :session, only: [:new, :create, :destroy]

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new 
    
    if user.admin?
        can :manage, :all
    end
    
    alias_action :create, :read, :update, :delete, to: :crud

    can :crud, Post do |post|
        user == post.user
    end

    can :crud, Comment do |comment|
        user == comment.user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user, optional: true
    
    validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user, optional: true
    
    validates :title, presence: true, uniqueness: {case_sensitive: false}
    validates :body, presence: true, length: {minimum: 50}

    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :name, presence: true
    validates :email, presence: true, uniqueness: {case_sensitive: false}, format: VALID_EMAIL_REGEX
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authenticated_user!
        unless user_signed_in?
            flash[:Alert] = "Please Sign In First"
            redirect_to root_path
        end
    end

    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?

    def current_user
        @current_user ||= User.find_by_id(session[:user_id])
    end
    helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_post
    before_action :authenticated_user!

    def create
        @comment = Comment.new(params.require(:comment).permit(:body))
        @comment.post = @post
        @comment.user = current_user
        if @comment.save
            redirect_to post_path(@post)
            flash[:Notice] = "Comment Added!"
        else
            @comments = @post.comments.order(created_at: :asc)
            flash[:Error] = @comment.errors.full_messages.to_sentence
            redirect_to post_path(@post), status: 303
        end
    end

    def destroy 
        @comment = Comment.find(params[:id])
        if can?(:crud, @comment) || can?(:crud, @post)
            @comment.destroy
            redirect_to post_path(@post) 
            flash[:Notice] = "Comment Deleted!"
        else
            redirect_to root_path
            flash[:Alert] = "Not Authorized!"
        end
    end

    private

    def find_post
        @post = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :destroy, :edit, :update]
    before_action :authenticated_user!, except: [:index, :show]
    before_action :authorize_user!, only: [:edit, :update, :destroy]

    def new 
        @post = Post.new
    end

    def create 
        @post = Post.new(post_params)
        @post.user = current_user
        if @post.save
            flash[:Notice] = "Post Created Successfully!"
            redirect_to post_path(@post)
        else
            flash[:Erorr] = @post.errors.full_messages.to_sentence
            render :new
        end
    end

    def index
        @posts = Post.order(created_at: :desc)
    end

    def show
        @comments = @post.comments.order(created_at: :asc)
        @comment = Comment.new
    end

    def destroy
        @post.destroy
        redirect_to posts_path
        flash[:Notice] = "Post Deleted!"
    end

    def edit
    end

    def update
        if @post.update(post_params)
            redirect_to post_path(@post)
            flash[:Notice] = "Post Updated!"
        else
            flash[:Error] = @post.errors.full_messages.to_sentence
            render :edit
        end
    end

    private

    def authorize_user!
        unless can?(:crud, @post)
            flash[:Alert] = "Not Authorized!"
            redirect_to root_path
        end
    end
    
    def find_post
        @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by_email(params[:email])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            flash[:Notice] = "Logged In!"
            redirect_to root_path
        else 
            flash[:Error] = "User Not Found!"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:Notice] = "Logged Out!"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:edit, :update, :change_password, :update_password]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:Notice] = "Logged In!"
            redirect_to root_path
        else
            flash[:Error] = @user.errors.full_messages.to_sentence
            render :new
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            redirect_to root_path
            flash[:Notice] = "User Updated!"
        else 
            flash[:Error] = @user.errors.full_messages.to_sentence
            render :edit
        end
    end

    def change_password
    end

    def update_password
        if @user && @user.authenticate(params[:current_password])
            if params[:new_password] != params[:current_password]
                if @user.update({password: params[:new_password], password_confirmation: params[:new_password_confirmation]})
                    redirect_to root_path
                    flash[:Notice] = "Password Updated!"
                else
                    flash[:Error] = @user.errors.full_messages.to_sentence
                    render :change_password
                end
            else
                flash[:Error] = "Cannot Use Old Password"
                render :change_password
            end
        else
            flash[:Error] = "That Is Not Your Current Password"
            render :change_password
        end
    end

    private 

    def find_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body id="body">
  <nav class="navbar navbar-expand navbar-light bg-light">
  <%= link_to "Blog On Rails", root_path, :class => "navbar-brand text-primary"%>
  <div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav">
  <li class="nav-item">
  <%= link_to "Home", posts_path, :class => "nav-link active text-primary" %>
  </li>
  <li class="nav-item">
  <%= link_to "New Post", new_post_path, :class => "nav-link active text-primary" %>
  </li>
  </ul>
  </div>
  </nav>
  <% if user_signed_in? %>
    Hello <%= link_to current_user.name, edit_user_path(current_user.id) %>,
    <%= link_to "Logout", session_path, method: :delete,
              data: {confirm: "Are You Sure You Want To Log Out?"}%>
  <% else %>
    <%= link_to "Login", new_session_path %> |
    <%= link_to "Sign Up", new_user_path %>
  <% end %>
  <hr>
  <% flash.each do |type, message| %>
  <div class="alert alert-info">
  <%= type + ": " + message %>
  </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_with model: @post do |form| %>
  <div class="form-group" id="title">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control"%>
  </div>
  <br>
  <%= form.submit :"Update Post", :class => "btn btn-outline-primary" %>
<% end %>

app/views/posts/index.html.erb
<div class="desktop">
<% @posts.in_groups_of(3) do |post_group|%>
<div class="row">
<% post_group.each do |post|%>
<% if post %>
<div class="col"> 
<div class="card">
    <div class="card-body">
        <h2><%= link_to post.title, post_path(post), class: "card-title" %></h2>
        <% preview = "" %>
        <% for i in 0..44 do %> 
        <% preview += post.body[i] %> 
        <% end %>
        <p class="card-text"><%= preview %>...</p>
    </div>
</div>
</div>
<% else %>
<div class="col">
</div>
<% end %>
<% end %>
</div>
<% end %>
</div>

<div class="tablet">
<% @posts.in_groups_of(2) do |post_group|%>
<div class="row">
<% post_group.each do |post|%>
<% if post %>
<div class="col"> 
<div class="card">
    <div class="card-body">
        <h2><%= link_to post.title, post_path(post), class: "card-title" %></h2>
        <% preview = "" %>
        <% for i in 0..44 do %> 
        <% preview += post.body[i] %> 
        <% end %>
        <p class="card-text"><%= preview %>...</p>
    </div>
</div>
</div>
<% else %>
<div class="col">
</div>
<% end %>
<% end %>
</div>
<% end %>
</div>

<div class="mobile">
<% @posts.each do |post| %>
<div class="card">
    <div class="card-body">
        <h2><%= link_to post.title, post_path(post), class: "card-title" %></h2>
        <% preview = "" %>
        <% for i in 0..44 do %> 
        <% preview += post.body[i] %> 
        <% end %>
        <p class="card-text"><%= preview %>...</p>
    </div>
</div>
<% end %>
</div>

app/views/posts/new.html.erb
<%= form_with model: @post do |form| %>
  <div class="form-group" id="title">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control"%>
  </div>
  <br>
  <%= form.submit :"Create Post", :class => "btn btn-outline-primary" %>
<% end %>

app/views/posts/show.html.erb
<h1 id="post"><%= @post.title %></h1>
<p><%= @post.body %></p> 
<p><%="By: " + @post.user.name %></p>
<p><small>Posted <%= time_ago_in_words(@post.created_at) %> ago</small></p>
<% if can?(:crud, @post) %>
<div id="buttons">
<%= button_to "Edit", edit_post_path, :method => :get, :class => "btn btn-outline-primary", :id => "edit"%>
<%= button_to "Delete", post_path(@post), method: :delete, :class => "btn btn-outline-primary", data: {confirm: "Are You Sure?"} %>
</div>
<% end %>
<br>

<h3>Comment</h3>
<%= form_with(model:[@post, @comment]) do |f| %>
<div id="comment">
<%= f.text_area :body, :class => "form-control", placeholder: "What's on your mind?" %>
</div>
<%= f.submit :Submit, :class => "btn btn-outline-primary" %>
<% end %>
<br> 

<% @comments.each do |comment| %>
<%= comment.body + " | By: " + comment.user.name.to_s %>
<div id="comments">
<p id="comment-time"><small>Commented <%= time_ago_in_words(comment.created_at) %> ago •</small></p>
<% if can?(:crud, comment) || can?(:crud, @post) %>
<%= link_to "Delete", post_comment_path(@post, comment), method: :delete, data: {confirm: "Are You Sure?"} %>
<% end %>
</div>
<% end %>

app/views/users/change_password.html.erb
<%= form_tag user_path, method: :post do %>
  <div class="form-group">
    <%= label_tag :current_password %>
    <%= password_field_tag :current_password, "", class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= label_tag :new_password %>
    <%= password_field_tag :new_password, "", class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= label_tag :new_password_confirmation %>
    <%= password_field_tag :new_password_confirmation, "", class: "form-control" %>
  </div>
  <br>
    <%= submit_tag :"Update Password", class: "btn btn-outline-primary" %>
<% end %>

app/views/users/edit.html.erb
<%= form_with model: @user do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <br>
    <%= submit_tag :"Update User", class: "btn btn-outline-primary" %>
<% end %>
<br>
<%= link_to "Change Password", user_path(@user) %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <br>
  <%= submit_tag :"Create User", class: "btn btn-outline-primary" %>
<% end %>